# Generated by Django 2.2 on 2021-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20210731_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartlist',
            name='cart_id',
            field=models.CharField(default=0, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
